apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloenv-staging
resources:
- namespace.yaml
- ../app
- service.yaml
- ingress.yaml
images:
- name: docker.io/shapai/helloenv
  newName: docker.io/shapai/helloenv # {"$imagepolicy": "flux-system:pypodinfo-staging:name"}
  newTag: Build-140 # {"$imagepolicy": "flux-system:pypodinfo-staging:tag"}
