apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloenv-staging
resources:
- namespace.yaml
- ../app
- service.yaml
- ingress.yaml
images:
- name: docker.io/shapai/helloenv
  newName: docker.io/shapai/helloenv # {"$imagepolicy": "flux-system:helloenv-staging:name"}
  newTag: Build-149 # {"$imagepolicy": "flux-system:helloenv-staging:tag"}
patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helloenv
    spec:
      template:
        spec:
          containers:
            - name: helloenv
              env:
                - name: ENV
                  value: "stage"
