apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloenv-staging
resources:
- namespace.yaml
- ../app
- service.yaml
- ingress.yaml
images:
- name: docker.io/shapai/helloenv
  newName: docker.io/shapai/helloenv # {"$imagepolicy": "flux-system:helloenv-staging:name"}
  newTag: Build-149 # {"$imagepolicy": "flux-system:helloenv-staging:tag"}
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        - name: ENV
          value: "stage"
  target:
    kind: Deployment
    namespace: helloenv-staging
    name: helloenv
