apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-env
  labels:
    app: hello-env
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-env
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-env
    spec:
      containers:
      - name: hello-env
        image: shapai/helloenv:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "stage"
