apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-env
  labels:
    app: hello-env
spec:
  type: ClusterIP
  selector:
    app: hello-env
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
